#!/usr/bin/env python3

"""
Module 6: Causal Graph Construction from LLM Chain-of-Thought Explanations

This module provides the interface for building weighted directed graphs from
causal chain-of-thought explanations generated by Module 5. It extracts
structured "feature → mechanism → outcome" triples and aggregates them into
a NetworkX graph for downstream rule extraction.

Main Components:
- CausalGraphBuilder: Core class implementing the graph construction pipeline
- run_causal_graph_construction: Main entry point for the module
- parameters: Configuration settings and regex patterns for parsing

The module takes causal explanations from Module 5, parses them using regex
patterns to extract causal relationships, and outputs a serialized NetworkX
graph with comprehensive edge statistics.

Key Features:
- Multiple regex patterns for robust triple extraction
- Feature validation against Module 4 selected features
- Weighted edges based on frequency of causal relationships
- Comprehensive mechanism and confidence tracking
- Graph visualization with NetworkX and matplotlib
- CSV export of edge weights and statistics

Usage:
    from module_6_causal_graph import run_causal_graph_construction
    
    graph = run_causal_graph_construction()

Input Requirements:
- artifacts/llm_output/causal.jsonl: Causal explanations from Module 5
- artifacts/feature_selection/selected_features.json: Valid features (optional)

Output Artifacts:
- artifacts/graphs/causal_graph.pkl: Serialized NetworkX DiGraph
- artifacts/graphs/edge_weights.csv: Edge statistics and mechanisms
- artifacts/graphs/graph_visualization.png: Visual representation (optional)

Note: Requires NetworkX library for graph construction and analysis.
"""

from .build_causal_graph import run_causal_graph_construction, CausalGraphBuilder
from . import parameters

__all__ = [
    'run_causal_graph_construction',
    'CausalGraphBuilder',
    'parameters'
] 